# ScribeChat v2.0 - Konfigurasi Utama
# Author: RifqyDev

api-settings:
  gemini-key: "INPUT_YOUR_GEMINI_API_KEY_HERE"

chat-format:
  # Format chat: {name} = Nama pemain, {msg} = Pesan
  global: "§8[§cG§8] §7{name} §8» §f{msg}"
  local: "§8[§aL§8] §7{name} §8» §f{msg}"
  staff: "§8[§eSTAFF§8] §c{name} §8» §e{msg}"

features:
  local-chat:
    enabled: true
    radius: 50 # Radius blok untuk Local Chat. Gunakan awalan "!" untuk Global Chat
  anti-spam:
    enabled: true
    cooldown-seconds: 3
    block-duplicate: true
  anti-capslock: true
  block-links: true # Memblokir IP server lain atau link tidak dikenal
  smart-mentions: true # Suara "Pop" saat nama di-tag (@nama)
  ai-grammar-fixer: true # AI merapikan singkatan/typo (contoh: "bng bg dmd" -> "Bang, bagi diamond")

webhook:
  discord-url: "" # Kosongkan jika tidak dipakai
