name: ScribeChat
version: 2.0.0
main: rifqydev\scribechat\Loader
api: ["5.0.0"]
author: RifqyDev
description: Ultimate Minimalist Chat Engine, AI Assistant, and Moderation for PM5.
commands:
  chat:
    description: "Membuka menu utama ScribeChat"
    permission: "scribechat.command.chat"
    usage: "/chat"
  sc:
    description: "Kirim pesan ke Staff Channel"
    permission: "scribechat.staff"
    usage: "/sc <pesan>"
permissions:
  scribechat.command.chat:
    default: true
  scribechat.staff:
    default: op
    description: "Akses membaca dan mengirim ke Staff Chat"
  scribechat.bypass:
    default: op
    description: "Bypass cooldown dan chat filter"
